export let projes = [
    {
        name:"Pizza",
        img:"/pizza.png",
        description:"A simple, customizable, minimal setup cookie plugin that allows your users to select which cookies to accept or decline. This was created with vanilla JS, SCSS and Parcel Bundler and is available as a NPM package and the git repository makes any type of customization to code and themes possible.",
        link1: "https://github.com/sevvalaksoy/S7PizzaChallenge",
        link2: "https://s7-pizza-challenge.vercel.app/",
    },
    {
        name:"Gratitude List",
        img:"/gratitude.png",
        description:"A simple, customizable, minimal setup cookie plugin that allows your users to select which cookies to accept or decline. This was created with vanilla JS, SCSS and Parcel Bundler and is available as a NPM package and the git repository makes any type of customization to code and themes possible.",
        link1: "https://github.com/sevvalaksoy/s10g5",
        link2: "https://s10g5.vercel.app/",
    },
    {
        name: "IMDB Movies",
        img: "/proje2.png",
        description:"A simple, customizable, minimal setup cookie plugin that allows your users to select which cookies to accept or decline. This was created with vanilla JS, SCSS and Parcel Bundler and is available as a NPM package and the git repository makes any type of customization to code and themes possible.",
        link1: "https://github.com/sevvalaksoy/fsweb-s10g2-redux-filmler-solution",
        link2: "https://fsweb-s10g2-redux-filmler-solution-kohl.vercel.app/movies"
    },
    {
        name:"Grid Game",
        img:"/proje3.png",
        description:"A simple, customizable, minimal setup cookie plugin that allows your users to select which cookies to accept or decline. This was created with vanilla JS, SCSS and Parcel Bundler and is available as a NPM package and the git repository makes any type of customization to code and themes possible.",
        link1: "https://github.com/sevvalaksoy/FSWeb-S9-Sprint-Challenge-solution",
        link2: "https://fsweb-s9-sprint-challenge-solution-1-p9nc.onrender.com/",
    },
    {
        name:"Movie List",
        img:"/proje1.png",
        description:"A simple, customizable, minimal setup cookie plugin that allows your users to select which cookies to accept or decline. This was created with vanilla JS, SCSS and Parcel Bundler and is available as a NPM package and the git repository makes any type of customization to code and themes possible.",
        link1: "https://github.com/sevvalaksoy/fsweb-s10g3-redux-watchlist-solution",
        link2: "https://fsweb-s10g3-redux-watchlist-solution-sand.vercel.app/",
    },
    {
        name:"Kripto Watcher",
        img:"/cripto.png",
        description:"A simple, customizable, minimal setup cookie plugin that allows your users to select which cookies to accept or decline. This was created with vanilla JS, SCSS and Parcel Bundler and is available as a NPM package and the git repository makes any type of customization to code and themes possible.",
        link1: "https://github.com/sevvalaksoy/sp9g3s2",
        link2: "https://sp9g3s2.vercel.app/",
    },
    {
        name:"Todo List",
        img:"/todo.png",
        description:"A simple, customizable, minimal setup cookie plugin that allows your users to select which cookies to accept or decline. This was created with vanilla JS, SCSS and Parcel Bundler and is available as a NPM package and the git repository makes any type of customization to code and themes possible.",
        link1: "https://github.com/sevvalaksoy/s9g2",
        link2: "https://s9g2.vercel.app/",
    },
    {
        name:"Contact Form",
        img:"/contact.png",
        description:"A simple, customizable, minimal setup cookie plugin that allows your users to select which cookies to accept or decline. This was created with vanilla JS, SCSS and Parcel Bundler and is available as a NPM package and the git repository makes any type of customization to code and themes possible.",
        link1: "https://github.com/sevvalaksoy/s9g4",
        link2: "https://s9g4.vercel.app/",
    },
    {
        name:"Calculator",
        img:"/calculator.png",
        description:"A simple, customizable, minimal setup cookie plugin that allows your users to select which cookies to accept or decline. This was created with vanilla JS, SCSS and Parcel Bundler and is available as a NPM package and the git repository makes any type of customization to code and themes possible.",
        link1: "https://github.com/sevvalaksoy/s10g1",
        link2: "https://s10g1.vercel.app/",
    },
    {
        name:"Product Chart",
        img:"/products.png",
        description:"A simple, customizable, minimal setup cookie plugin that allows your users to select which cookies to accept or decline. This was created with vanilla JS, SCSS and Parcel Bundler and is available as a NPM package and the git repository makes any type of customization to code and themes possible.",
        link1: "https://github.com/sevvalaksoy/s11g2",
        link2: "https://s11g2.vercel.app/",
    },
    {
        name:"Friends",
        img:"/friends.png",
        description:"A simple, customizable, minimal setup cookie plugin that allows your users to select which cookies to accept or decline. This was created with vanilla JS, SCSS and Parcel Bundler and is available as a NPM package and the git repository makes any type of customization to code and themes possible.",
        link1: "https://github.com/sevvalaksoy/s11g1",
        link2: "https://s11g1.vercel.app/login",
    },
    {
        name:"WiContacts",
        img:"/wicontacts.png",
        description:"A simple, customizable, minimal setup cookie plugin that allows your users to select which cookies to accept or decline. This was created with vanilla JS, SCSS and Parcel Bundler and is available as a NPM package and the git repository makes any type of customization to code and themes possible.",
        link1: "https://github.com/sevvalaksoy/s10g4",
        link2: "https://s10g4.vercel.app/",
    },
    {
        name:"WiStore",
        img:"/WiStore.png", 
        description:"A simple, customizable, minimal setup cookie plugin that allows your users to select which cookies to accept or decline. This was created with vanilla JS, SCSS and Parcel Bundler and is available as a NPM package and the git repository makes any type of customization to code and themes possible.",
        link1: "https://github.com/sevvalaksoy/s9g3",
        link2: "https://s9g3.vercel.app/",
    },
    {
        name:"CRUDs",
        img:"/CRUD.png",
        description:"A simple, customizable, minimal setup cookie plugin that allows your users to select which cookies to accept or decline. This was created with vanilla JS, SCSS and Parcel Bundler and is available as a NPM package and the git repository makes any type of customization to code and themes possible.",
        link1: "https://github.com/sevvalaksoy/s11g3",
        link2: "https://s11g3.vercel.app/movies",
    },
    
]